version: "2"
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    config:
      threshold: 1000
  method-count:
    enabled: false
engines:
      duplication:
        enabled: true
        config:
          languages:
            python:
              python_version: 3
              mass_threshold: 40
